In [1]:
import cv2 as cv
import numpy as np

In [6]:
classifier = cv.CascadeClassifier('haarcascade_frontalface_default.xml')

cam = cv.VideoCapture(1)

while True:
    
    _, img = cam.read()
    img = cv.flip(img,1)
    
    faces = classifier.detectMultiScale(img, 1.1, 5)
    
    for f in faces:                             # Going through Each Face Detected
        if f[-1] == max(faces[:,-1]):           # Finding the Face with Maximum Area
            break 

    if (len(faces) >= 1):                       # Drawing Rectange on the Face
        x = f[0] 
        y = f[1] 
        w = f[2]
        h = f[3]

        cv.rectangle(img, (x,y),(x+w,y+h) , (0,180,0), 2)   
        face = img[y:y+h, x:x+w]
        
        face = cv.resize(face, (256,256))

    cv.imshow('Frame'  , img )
    cv.imshow('Face'   , face)
    
    if cv.waitKey(1) == 27:
        cam.release()
        break

In [3]:
cam.release()

In [7]:
list(face)

[array([[  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],


In [8]:
face[0], face[1], face[2], face[3]

(array([[  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],
        [  0, 180,   0],


In [9]:
faces[0]

array([180, 255, 197, 197])

In [10]:
for face in faces:
    if face[-1] == max(faces[:,-1]):
        print(face)

[180 255 197 197]
