In [1]:
import cv2 as cv
import numpy as np

In [2]:
classifier = cv.CascadeClassifier('haarcascade_frontalface_default.xml')

cam = cv.VideoCapture(1)

while True:
    
    _, img = cam.read()
    img = cv.flip(img,1)
    
    faces = classifier.detectMultiScale(img, 1.1, 5)
    
    for f in faces:
        if f[-1] == max(faces[:,-1]):
            break

    if (len(faces) >= 1):
        x = f[0] 
        y = f[1] 
        w = f[2]
        h = f[3]

#         cv.rectangle(img, (x,y),(x+w,y+h) , (0,180,0), 2)   

        face = img[y:y+h, x:x+w]                 # Getting the Face Area from Video Feed
        face = cv.blur(face, (32,32))            # Applying Blur on the Face
        img[y:y+h, x:x+w] = face                 # Apply Blured Face on Video Feed
        

    cv.imshow('Frame'  , img )
    cv.imshow('Face'   , face)
    
    if cv.waitKey(1) == 27:
        cam.release()
        break


In [3]:
cam.release()

In [4]:
list(face)

[array([[132, 134, 149],
        [132, 134, 149],
        [132, 134, 149],
        [131, 133, 148],
        [131, 133, 148],
        [130, 132, 147],
        [129, 131, 146],
        [128, 130, 145],
        [127, 128, 143],
        [125, 127, 142],
        [123, 125, 140],
        [121, 122, 137],
        [118, 120, 134],
        [116, 117, 131],
        [113, 114, 128],
        [110, 111, 125],
        [107, 108, 121],
        [104, 104, 118],
        [100, 101, 114],
        [ 97,  97, 110],
        [ 94,  94, 106],
        [ 91,  91, 103],
        [ 87,  87,  99],
        [ 84,  84,  95],
        [ 81,  80,  91],
        [ 78,  77,  88],
        [ 75,  74,  84],
        [ 71,  70,  81],
        [ 68,  67,  77],
        [ 65,  63,  74],
        [ 62,  60,  70],
        [ 59,  57,  67],
        [ 57,  54,  64],
        [ 54,  51,  61],
        [ 51,  48,  59],
        [ 49,  46,  56],
        [ 47,  43,  54],
        [ 45,  41,  51],
        [ 42,  39,  49],
        [ 40,  37,  47],


In [5]:
face[0], face[1], face[2], face[3]

(array([[132, 134, 149],
        [132, 134, 149],
        [132, 134, 149],
        [131, 133, 148],
        [131, 133, 148],
        [130, 132, 147],
        [129, 131, 146],
        [128, 130, 145],
        [127, 128, 143],
        [125, 127, 142],
        [123, 125, 140],
        [121, 122, 137],
        [118, 120, 134],
        [116, 117, 131],
        [113, 114, 128],
        [110, 111, 125],
        [107, 108, 121],
        [104, 104, 118],
        [100, 101, 114],
        [ 97,  97, 110],
        [ 94,  94, 106],
        [ 91,  91, 103],
        [ 87,  87,  99],
        [ 84,  84,  95],
        [ 81,  80,  91],
        [ 78,  77,  88],
        [ 75,  74,  84],
        [ 71,  70,  81],
        [ 68,  67,  77],
        [ 65,  63,  74],
        [ 62,  60,  70],
        [ 59,  57,  67],
        [ 57,  54,  64],
        [ 54,  51,  61],
        [ 51,  48,  59],
        [ 49,  46,  56],
        [ 47,  43,  54],
        [ 45,  41,  51],
        [ 42,  39,  49],
        [ 40,  37,  47],


In [6]:
faces[0]

array([147, 230, 193, 193])

In [7]:
for face in faces:
    if face[-1] == max(faces[:,-1]):
        print(face)

[147 230 193 193]
